//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchet
    {
        public decimal ID { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Materiali { get; set; }
        public decimal Price { get; set; }
        public string Prichina_neispravnosti { get; set; }
        public System.DateTime Data_create { get; set; }
        public decimal ID_zajavki { get; set; }
    
        public virtual Zajavka Zajavka { get; set; }
    }
}
