//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajavka()
        {
            this.Otchet = new HashSet<Otchet>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_ispolnitel { get; set; }
        public string Tip_neispravnosti { get; set; }
        public string Serijni_number { get; set; }
        public string Information { get; set; }
        public string Priopitet { get; set; }
        public System.DateTime Date_create { get; set; }
        public decimal ID_status { get; set; }
        public decimal ID_client { get; set; }
        public decimal ID_oborudovanie { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otchet> Otchet { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
